/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaNegocio.Empresa;
import CapaNegocio.Entidades.EntidadPais;
import CapaNegocio.Pais;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO-510
 */
public class frmRegistroEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroEmpresa
     */
    public frmRegistroEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null);
        Llenar_pais();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Empresa objE =null;
    
    public static String contraseña = "";
    public int empresaid =0;
    public String imagenselect = "";
    public String archivoIdiomaselect = "";
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPostulante = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboPais = new javax.swing.JComboBox<>();
        btnSeleccionarFoto = new javax.swing.JButton();
        btnVerFoto = new javax.swing.JButton();
        btnSiguientePostulante = new javax.swing.JButton();
        cboTipoEmpresa = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        btnSunat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPostulante.setBackground(new java.awt.Color(255, 255, 255));
        panelPostulante.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel2.setText("RUC:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Foto");

        jLabel6.setText("Tipo");

        jLabel11.setText("Pais");

        btnSeleccionarFoto.setBackground(new java.awt.Color(0, 117, 196));
        btnSeleccionarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarFoto.setText("Seleccionar foto");
        btnSeleccionarFoto.setEnabled(false);
        btnSeleccionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFotoActionPerformed(evt);
            }
        });

        btnVerFoto.setBackground(new java.awt.Color(0, 117, 196));
        btnVerFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnVerFoto.setText("Ver");
        btnVerFoto.setEnabled(false);
        btnVerFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFotoActionPerformed(evt);
            }
        });

        btnSiguientePostulante.setBackground(new java.awt.Color(0, 117, 196));
        btnSiguientePostulante.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguientePostulante.setText("Resgistrar");
        btnSiguientePostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePostulanteActionPerformed(evt);
            }
        });

        cboTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAC", "SA", "SRL", "SAA" }));

        jLabel30.setBackground(new java.awt.Color(0, 117, 196));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 117, 196));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Registrar Empresa");

        btnSunat.setBackground(new java.awt.Color(0, 117, 196));
        btnSunat.setForeground(new java.awt.Color(255, 255, 255));
        btnSunat.setText("Sunat");
        btnSunat.setEnabled(false);
        btnSunat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSunatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPostulanteLayout = new javax.swing.GroupLayout(panelPostulante);
        panelPostulante.setLayout(panelPostulanteLayout);
        panelPostulanteLayout.setHorizontalGroup(
            panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostulanteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPostulanteLayout.createSequentialGroup()
                        .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPostulanteLayout.createSequentialGroup()
                                .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSunat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostulanteLayout.createSequentialGroup()
                                .addComponent(btnSeleccionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNombre)
                            .addComponent(cboTipoEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPais, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPostulanteLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnSiguientePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPostulanteLayout.setVerticalGroup(
            panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostulanteLayout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPostulanteLayout.createSequentialGroup()
                        .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSunat))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostulanteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPostulanteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnSeleccionarFoto)
                    .addComponent(btnVerFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSiguientePostulante)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFotoActionPerformed
        //grabarImagen();
    }//GEN-LAST:event_btnSeleccionarFotoActionPerformed

    private void btnVerFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFotoActionPerformed
        /*if (imagenselect.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una imagen primero");
        } else {
            JDialog jd = new JDialog(this);
            JPanel jp = new JPanel();
            jd.add(jp);
            JLabel jl = new JLabel();
            ImageIcon imagen = new ImageIcon(imagenselect);
            jl.setIcon(imagen);
            jp.setLayout(new GridBagLayout());
            jp.add(jl);
            jp.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
            jd.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            jd.setSize(500, 500);
            jd.setLocationRelativeTo(null);
            jd.setTitle("Previsualización de la imagen");
            jd.setVisible(true);
        }*/
    }//GEN-LAST:event_btnVerFotoActionPerformed

    private void btnSiguientePostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePostulanteActionPerformed
        Registrar_Empresa();
    }//GEN-LAST:event_btnSiguientePostulanteActionPerformed

    private void btnSunatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSunatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSunatActionPerformed
    
    private void grabarImagen() {
        JFileChooser imagenseleccionada = new JFileChooser();
        int seleccion = imagenseleccionada.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File imagen = imagenseleccionada.getSelectedFile();
            if (obtenerExtension(imagen).equalsIgnoreCase("png") || obtenerExtension(imagen).equalsIgnoreCase("jpg") || obtenerExtension(imagen).equalsIgnoreCase("gif")) {
                StringBuilder path = new StringBuilder();
                path.append(imagen.getAbsolutePath());
                imagenselect = path.toString();
            } else {
                JOptionPane.showMessageDialog(this, "La imagen debe ser PNG, JPG o GIF");
                imagenselect = "";
            }
        }
    }
    
    private String obtenerExtension(File f) {
        String ext = null;
        String s = f.getName();
        int i = s.lastIndexOf('.');

        if (i > 0 && i < s.length() - 1) {
            ext = s.substring(i + 1).toLowerCase();
        }
        return ext;
    }
    
    private void Registrar_Empresa(){
        try {
            if(txtRUC.getText().isEmpty() || txtNombre.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Complete todos los campos");
            }else{
                if (txtRUC.getText().length() != 11){
                    JOptionPane.showMessageDialog(this, "Corriga el ruc con los 11 digitos correspondientes");
                }else{
                    objE = new Empresa();

                    objE.setRuc(txtRUC.getText());
                    objE.setNombre_empresa(txtNombre.getText());
                    objE.setTipo_empresa(cboTipoEmpresa.getSelectedItem().toString());
                    objE.setContraseña(contraseña);
                    EntidadPais pais = (EntidadPais) cboPais.getSelectedItem();
                    objE.setPais_id(pais.getPais_id());

                    empresaid=objE.registrarEmpresa();
                    JOptionPane.showMessageDialog(this, "Se registró a la empresa");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()+ objE.getTipo_empresa());
        }
    }
    private void Llenar_pais () {
        try{
            Pais objPais = new Pais();
            ArrayList<EntidadPais> paises = objPais.llenarPais();
            cboPais.setModel(new DefaultComboBoxModel(paises.toArray()));
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarFoto;
    private javax.swing.JButton btnSiguientePostulante;
    private javax.swing.JButton btnSunat;
    private javax.swing.JButton btnVerFoto;
    private javax.swing.JComboBox<String> cboPais;
    private javax.swing.JComboBox<String> cboTipoEmpresa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelPostulante;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUC;
    // End of variables declaration//GEN-END:variables
}
